[python cli] 'rtw docker enter'
StoglRobotics/ros_team_workspace pull request #126
Opened 2023-04-29 12:59 UTC by muritane

just run this `cd ros_team_workspace/rtwcli/ && pip3 install -r requirements.txt` and start new terminal as sourcing is already done in _ros_team_workspace/setup.bash_

@destogl pep257 is commented out temporarily as the import of Set raises Exception: `cannot import name 'Set' from 'collections'`, is there a repo that supports newer python versions?

2023-05-02 08:59 UTC, mamueluth commented
Nice work! Looks good:) 
I would however advise to first create only the cli and call the existing bash scripts with the expected arguments. I would not start recreating/adding logic in the python cli. This should in my opinion be done in a separate step while writing tests at the same time.
Moreover, in my opinion, we have a lot of common functionality which can be extracted from the scripts and collected at one point. I would keep the cli as thin as possible and not scatter to much logic all over the place (otherwise we end up with lot of duplicate logic.)

2023-05-02 08:59 UTC, mamueluth commented
Have to give it a closer review

2023-05-02 09:04 UTC, destogl commented
> @destogl pep257 is commented out temporarily as the import of Set raises Exception: cannot import name 'Set' from 'collections', is there a repo that supports newer python versions?

I fixed that.

2023-05-02 09:27 UTC, destogl requested changes
As much as I agree with @mamueluth, we should keep effort in reusing bash commands low.

In general, this looks excellent to me. Still, there are a few open questions to clarify:

1. Can we reduce the number of folders and files by adding all commands into one package? (so we end up having only two packages?)
2. What will happen if I execute `auto-source` one more time? will I break my current setup?
3. we should split this into multiple PRs. - 1. with base setup also initial command, 2. with dokcer setup, 3. with package setup.
4. Initial setup should add `info` command giving info output about rtw setup. For now let just output the base path of the package. We can add later other stuff.

2023-05-02 09:27 UTC, destogl commented on rtwcli/.gitignore
Please use `.gitignore` inside your $HOME folder. We can also add this into templates for setting up default fiel when setting up RTW.

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/completion/rtw-argcomplete.bash
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
Add our license.

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/cli.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
Add our license

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/cli.py
> +        description = f"{script_name} is an extensible command-line tool " "for ROS Team WS."
```suggestion
        description = f"{script_name} is an extensible command-line tool " "for ROS Team Workspace."
```

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/command/__init__.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
our license

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/command/__init__.py
> +    )
Do we need this depreacation notice?

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/command/extension_points.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
our license

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/command/extensions.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
our license

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/entry_points.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
our license

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwcli/rtwcli/plugin_system.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
our license

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwdocker/rtwdocker/__init__.py
can we use `rtw_docker` as a package name? I find it easier to read and faster to see what is happening.

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwdocker/rtwdocker/api/__init__.py
> +    subprocess.run(["docker", "start", container_instance_name])
we should also fallback here to use existing rtw command. Then we move one by one - removing the old one and adding new one

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwdocker/rtwdocker/verb/__init__.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
license

2023-05-02 09:27 UTC, destogl commented on rtwcli/rtwpkg/rtwpkg/verb/__init__.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
license

2023-05-04 14:44 UTC, destogl commented on rtwcli/rtwcli/completion/rtw-argcomplete.bash
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright (c) 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-04 14:44 UTC, destogl commented on rtwcli/rtwcli/completion/rtw-argcomplete.zsh
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright (c) 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-04 14:52 UTC, destogl commented on rtwcli/rtwcli/rtwcli/cli.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2016-2017 Dirk Thomas
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright (c) 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-04 14:53 UTC, destogl commented on rtwcli/rtwcli/rtwcli/plugin_system.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2016-2017 Dirk Thomas
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright (c) 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-04 14:54 UTC, destogl commented on rtwcli/rtwcli/rtwcli/command/__init__.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2016-2017 Dirk Thomas
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-04 14:54 UTC, destogl commented on rtwcli/rtwcli/rtwcli/command/extension_points.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2016-2017 Dirk Thomas
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-04 14:55 UTC, destogl commented on rtwcli/rtwcli/rtwcli/entry_points.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2016-2017 Dirk Thomas
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-04 14:55 UTC, destogl commented on rtwcli/rtwpkg/rtwpkg/verb/__init__.py
> +# Copyright 2017 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2017-2023 Open Source Robotics Foundation, Inc.
# Copyright 2023, Stogl Robotics Consulting UG (haftungsbeschränkt)
```

2023-05-05 11:38 UTC, muritane commented
will be split into multiple prs

2023-05-05 11:38 UTC, closed without merging