[rtwcli] rtw cli base package with dummy info command
StoglRobotics/ros_team_workspace pull request #128
Opened 2023-05-05 11:26 UTC by muritane

2023-05-05 14:41 UTC, destogl requested changes
Just few things to clarify!

2023-05-05 15:57 UTC, muritane commented on rtwcli/rtwcli/rtwcli/command/extension_points.py
`~$ rtw extensions` What extensions are available?
```
rtw_cmds.docker.verbs
  enter: Enter docker container
rtw_cmds.pkg.verbs
  create: Create a new ROS package
rtwcli.command
  docker: Various Docker related sub-commands
  extension_points: List extension points
  extensions: List extensions
  info: Provide useful information
  pkg: Various package related sub-commands
```

`~$ rtw extension_points` What extension _interfaces_ are available?
```
rtw_cmds.docker.verbs: The interface for verb extensions
rtw_cmds.pkg.verbs: The interface for verb extensions
rtwcli.command: The extension point for 'command' extensions
```
For our case "extension_points" are not really necessary as we use the base verb from rtwcli.VerbExtension and base command from rtw_cmds.BaseCommmand. Should I remove extension_points?

2023-05-05 15:59 UTC, muritane commented on rtwcli/rtwcli/rtwcli/command/__init__.py
> +        "'rtwcli.command.add_subparsers_on_demand' instead",
removed the deprecated method

2023-05-12 07:04 UTC, destogl submitted a review, later dismissed
looks great!

2023-05-12 07:04 UTC, destogl commented on rtwcli/rtwcli/rtwcli/command/__init__.py
> +    The extension point for 'command' extensions.
```suggestion
    The extension point for 'command' extensions. Those are the base extensions in RTW.
```

2023-05-12 07:05 UTC, destogl approved these changes

2023-05-12 07:05 UTC, merged