Add Flag to Disable Automatic Upgrades in Script
StoglRobotics/ros_team_workspace pull request #233
Opened 2024-08-29 15:37 UTC by sachinkum0009

This pull request introduces a new command-line flag `--disable-upgrade` to control the automatic upgrade process during the script execution.

This enhancement provides more control over the upgrade process, particularly useful in environments where upgrades need to be managed separately or manually.

2024-08-30 09:40 UTC, mamueluth commented
LGTM just some nitpicking on the help message.

2024-08-30 09:41 UTC, mamueluth commented
Thanks for the nice work:)

2024-09-01 13:03 UTC, muritane commented
Missed in the first review: remove this flag from import verb as it is not used there and therefore not needed

2024-09-01 13:04 UTC, muritane requested changes
Missed in the first review: remove this flag from import verb as it is not used there and therefore not needed

2024-09-03 10:17 UTC, mamueluth approved these changes

2024-09-03 10:18 UTC, mamueluth approved these changes

2024-09-03 10:20 UTC, muritane approved these changes

2024-09-03 10:21 UTC, merged