WIP: UPDATE code generation for ros2_control components, docs ADD docker images for test env
StoglRobotics/ros_team_workspace pull request #24
Opened 2022-01-19 15:24 UTC by mamueluth

Code generation:
Code generation for controllers compiles, this should be checked though. Has warnings regarding unused parameter in update(...) function. Was not sure how to adjust update function. Besides test file should be checked if correct node time is used.

Docs:
updated getting stared, installation and building, create workspace.

Docker:
added two containers in test/test_container_docker which can be used as test env for ros team workspace

lot of changes are because of pre-commit, which make the pull request hard read (sry) but they are isolated in one commit.

2022-01-20 05:00 UTC, destogl requested changes
split this into multiple PR. They should be done feature-wise.

2022-01-20 05:00 UTC, destogl commented on test/test_container_docker/ubuntu_20_04_ros2_multi/bashrc
> +# ~/.bashrc: executed by bash(1) for non-login shells.
we should add "main" folder for this files and the same files should e only sym-linked for specific versions

2022-01-24 14:06 UTC, mamueluth commented on .gitignore
> +shell.nix
what about the docs/venv (.venv)? If people want to change the docs they have to use python and sphinx for preview. if they follow the Readme.md i added they likely going to use pip. Therefor the docs/venv folder is likely created.

2022-01-24 14:26 UTC, mamueluth commented on _team_config/defines.bash
> -
To be honest i don't know. Probably and editor issue. Also i can't remember opening the file.

2022-01-25 13:25 UTC, destogl commented on templates/ros2_control/controller/controller.cpp
> +controller_interface::return_type $ClassName$::update(const rclcpp::Time & time, const rclcpp::Duration & period)
```suggestion
controller_interface::return_type $ClassName$::update(const rclcpp::Time & time, const rclcpp::Duration & /*period*/)
```

2022-02-05 19:35 UTC, destogl commented
Obsolete PR – spited into multiple ones., so closing.

2022-02-05 19:35 UTC, closed without merging